### ISSUE TITLE
Deal with GPS / position data

### ISSUE THREAD

**Issue by Tobias-Fischer** [neuromorphs/tonic#101]
In the VPR dataset, we have GPS data. It would be great if we can incorporate that data as well. I use a super simple script at the moment to do that:

https://github.com/Tobias-Fischer/ensemble-event-vpr/blob/master/read_gps.py

**Comment by biphasic** [comment]
I think that's a great idea, the pynmea2 package also looks solid. Feel free to incorporate your code, otherwise I will try to have a look at it within the next 2 weeks.

**Comment by biphasic** [comment]
added in cdf3f7e48077411d00ffac5451789dc9208e9434

will be part of release version 1 of Tonic
