### ISSUE TITLE
cropping transformation doesn't affect sensor size

### ISSUE THREAD

**Issue by biphasic** [neuromorphs/tonic#110]
maybe that's okay, but when building frame representations from the events afterwards, the frames are not cropped because they use dataset.sensor_size

**Comment by neworderofjamie** [comment]
I think this is a more general problem - same thing happens with ``SubSample``

**Comment by biphasic** [comment]
fixed in v0.4.6. See [here](https://tonic.readthedocs.io/en/latest/release_notes.html#id1)
