### ISSUE TITLE
Incorporate hdf5-to-rosbag conversion

### ISSUE THREAD

**Issue by Tobias-Fischer** [neuromorphs/tonic#114]
More a FYI than an actual issue - check this out: https://github.com/tub-rip/events_h52bag

**Comment by biphasic** [comment]
thanks a lot for the link Tobias! I'm probably missing the point, could you explain how the h5 to rosbag conversion is going to help us? The way I see it, h5py already provides very good support for h5 file reading.

**Comment by Tobias-Fischer** [comment]
Yes, you are totally right. `h5` does a great job. Some people might want to use rosbags for whatever reason, and I thought it's nice for them to have a reference here somewhere that such a project exists. But for tonic directly there is indeed no good use, so I'm closing this issue.
