### ISSUE TITLE
Provide peer-to-peer links to increase download speed and resilience

### ISSUE THREAD

**Issue by Jegp** [neuromorphs/tonic#116]
Thanks for a great library! We're starting to rely on it quite a bit at my group.

I can see some datasets, such as the NMNIST, relies on a Dropbox link. This may make complete sense, but it may also be beneficial to use decentralized peer-to-peer services using, for instance, [IPFS](http://ipfs.io/). That should make the datasets more resilient to link expiration, service outage, and download bandwidth.

This could also be coupled with #111 to decrease the download size and increase unpacking/processing speed.

**Comment by biphasic** [comment]
thank you for this suggestion. I like IPFS as a technology. Something to keep in mind: Some dataset owners might not like us mirroring their dataset so we have to get permissions.

**Comment by Jegp** [comment]
Certainly, we shouldn't upload anything we're not allowed to :-)

**Comment by biphasic** [comment]
using IPFS would help with fault tolerance but only if someone is uploading and pinning the datasets on a node. Plus users need to install IPFS externally. Closing for the moment
