### ISSUE TITLE
NMNIST file integrity fails

### ISSUE THREAD

**Issue by Jegp** [neuromorphs/tonic#117]
After a successful download and extraction of the NMNIST dataset, the `check_integrity` check keeps failing for consecutive calls. Resulting in the zip file being extracted every time the dataset is being applied.

The expected behaviour would be to reuse the existing directory structure in the `./data/nmnist/` folder.

**Comment by Jegp** [comment]
Hope you don't mind me opening up issues. I'll be happy to look into them later.

**Comment by rob-luke** [comment]
I see there is already quite some code to handle downloading, extraction etc. An alternative to handling these issues is to offload to something like pooch https://github.com/fatiando/pooch Just an FYI, as we battle the same issues and are considering switching too.

**Comment by Jegp** [comment]
I really like that idea. It seems like a problem we shouldn't hack, but find more robust solutions to.

**Comment by biphasic** [comment]
great ideas! I appreciate your comments and I would like to find a robust solution too. Until now I just copied the download functions from https://github.com/pytorch/vision/blob/master/torchvision/datasets/utils.py, but relying on copied code is not good.
