### ISSUE TITLE
Should polarity be another sensor size dimension

### ISSUE THREAD

**Issue by neworderofjamie** [neuromorphs/tonic#122]
i.e. SHD would have a sensor size of (700,) and a "tx" ordering to indicate it has no polarity and a DVS128 dataset would have a sensor size of (128,128,2) and a "xypt" ordering. Without this, the only way of knowing the actual number of input neurons is to check whether there are different polarities in the "p" row.

Sorry for making so many issues 😄

**Comment by biphasic** [comment]
don't be sorry, I appreciate it! I think that's a good idea. But then it would need to be (700,1,1) and (128,128,2) for consistency, no?

**Comment by neworderofjamie** [comment]
Yeah, that would be better still. You could also go one step further and replace ``ordering`` altogether by returning events as a structured numpy array. That way you could also have x, y and b as integers which would save a lot of rounding horror when resampling etc.

**Comment by biphasic** [comment]
you mean in order to get rid of 'ordering' completely? I do like that. I will think about this more seriously and see if I can come up with some edge cases. We just started off with pure np arrays but I think you have another point there :) I appreciate your feedback!

**Comment by biphasic** [comment]
@neworderofjamie using dtypes and 3-tuple sensor size now :) PR: https://github.com/neuromorphs/tonic/pull/140
