### ISSUE TITLE
Why float type for events?

### ISSUE THREAD

**Issue by eneftci** [neuromorphs/tonic#125]
I'm wondering why one would use a float type to return address-events, for example here:
https://github.com/neuromorphs/tonic/blob/cec563ef97c7c5b522bca3d08cf7c1262eb6ec3f/tonic/datasets/nmnist.py#L176

In neuromorphic sensors or hardware, addresses generally results from AER and are thus better encoded as unsigned integers

**Comment by Jegp** [comment]
We had one issue (https://github.com/norse/norse/issues/228) where gradients in PyTorch don't flow properly when you specify the correct datatype. We've fixed that for Norse, but there may be other similar situations that @biphasic would know :-)  

I would also be interested in knowing how much this actually matters. How much memory + processing is saved from using bytes in Numpy/Torch?

**Comment by eneftci** [comment]
> We had one issue ([norse/norse#228](https://github.com/norse/norse/issues/228)) where gradients in PyTorch don't flow properly when you specify the correct datatype. 

I can't imagine a case where gradients should flow through input events.

**Comment by biphasic** [comment]
the issue @Jegp mentioned was in a ToSparseTensor transform, so not directly related to the event format. The main reason why I convert all events to floats was that some datasets use float time resolution (e.g. MVSEC) and I changed other dataset formats too to have equal inputs for transformations such as Spatial/TimeJitter or time dilation. It's something that's been on my mind recently and I haven't figured out a good solution. I will start a discussion here on github and tag you guys

**Comment by biphasic** [comment]
https://github.com/neuromorphs/tonic/discussions/126

**Comment by biphasic** [comment]
now using dtypes for datasets https://github.com/neuromorphs/tonic/pull/140
