### ISSUE TITLE
Add time_first parameter for tensor transformations

### ISSUE THREAD

**Issue by biphasic** [neuromorphs/tonic#130]
some simulators such as Norse and SNNTorch use time x batch x channels dimensions. In order to save one permute call, we can introduce this additional parameter

**Comment by Jegp** [comment]
This is btw also the default behaviour in [PyTorch](https://pytorch.org/docs/stable/generated/torch.nn.RNN.html#torch.nn.RNN).

**Comment by biphasic** [comment]
oh very good! I didn't know that. Thanks for that :) Then I will adopt the same convention

**Comment by biphasic** [comment]
Time first is now default, with an option to collate batches using batch_first as well
https://github.com/neuromorphs/tonic/blob/develop/tonic/collation.py#L7
