### ISSUE TITLE
Add TUMVIE navigation dataset

### ISSUE THREAD

**Issue by Jegp** [neuromorphs/tonic#139]
The TUMVIE visual inertial event dataset could be interesting for Tonic: https://vision.in.tum.de/data/datasets/visual-inertial-event-dataset

It's public under CC BY 4.0

**Comment by biphasic** [comment]
very nice, thanks for mentioning that one!

**Comment by biphasic** [comment]
now included in Tonic 1.0.9! https://tonic.readthedocs.io/en/latest/reference/datasets.html#tum-vie
