### ISSUE TITLE
Add some Prophesee datasets

### ISSUE THREAD

**Issue by biphasic** [neuromorphs/tonic#143]
apart from NCARS, which we already have, it would be nice to have access to some Gen4 camera datasets: https://docs.prophesee.ai/stable/datasets.html#datasets

**Comment by fabhertz95** [comment]
Hi! I saw that you mentioned that NCARS is already available in Tonic but I am not able to find it. Is it hidden in some other datasets? Or it has been removed (maybe due to the fact that at [this link](https://dataset.prophesee.ai/index.php/s/WUXbCrQMN6jg9oQ/download?path=%2F&files=Prophesee_Dataset_n_cars.7z) they ask every time for user information before downloading?)

**Comment by biphasic** [comment]
it used to be in there but I removed it (see this commit https://github.com/neuromorphs/tonic/commit/a7d78a747477b24eaf6fa4a1fbd56c58eca5b0ff)
because in order to read the files, I was dependent on the loris package https://github.com/neuromorphic-paris/loris
but that one is a compiled package and it created some issues. I thought that it would be nice to put some newer Prophesee datasets in place but when I looked at it the other day, it seems that they provide their data in their custom format .dat (which loris is able to read) a lot of the times still... Which dataset would you like to work on? The original NCARS with two classes?

**Comment by fabhertz95** [comment]
Yes, I need to work with the dataset from the original HATS paper. Do you suggest to manually download NCARS from their website and use loris to handle it? 
Of course, it would be nice to write a DAT processing function and integrate it in Tonic. Do you think it is feasible and that it makes sense?

**Comment by fabhertz95** [comment]
I noticed something: on [this line](https://github.com/neuromorphs/tonic/blob/bc9fd1317a709c291bc0f16881d2ee7de2a2fcb6/tonic/io.py#L25), loris is used directly without the try/except block. In fact, `read_aedat4()` is used also in [CIFAR10DVS](https://github.com/neuromorphs/tonic/blob/bc9fd1317a709c291bc0f16881d2ee7de2a2fcb6/tonic/datasets/cifar10dvs.py#L90) to read the file. Hence, we can simply restore the N-CARS dataset, add a try/except statement for loris in `read_aedat4()` and everything should be fine, right? Am I missing something?

**Comment by biphasic** [comment]
Good point! Please try this. Thank you 🙏

Le 20 avril 2022 15:09:56 GMT+01:00, Fabrizio Ottati ***@***.***> a écrit :
>I noticed something: on [this line](https://github.com/neuromorphs/tonic/blob/bc9fd1317a709c291bc0f16881d2ee7de2a2fcb6/tonic/io.py#L25), loris is used directly without the try/except block. In fact, `read_aedat4()` is used also in [CIFAR10DVS](https://github.com/neuromorphs/tonic/blob/bc9fd1317a709c291bc0f16881d2ee7de2a2fcb6/tonic/datasets/cifar10dvs.py#L90) to read the file. Hence, we can simply restore the N-CARS dataset, add a try/except statement for loris in `read_aedat4()` and everything should be fine, right? Am I missing something?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/neuromorphs/tonic/issues/143#issuecomment-1103979579
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by biphasic** [comment]
After getting in touch with Prophesee, they informed me that they plan on releasing more hdf5 datasets / files with their next release in September. Let's hope for the best!

**Comment by biphasic** [comment]
closing as we now have https://github.com/neuromorphs/tonic/issues/231 and https://github.com/neuromorphs/tonic/issues/230
