### ISSUE TITLE
Specific sequence from DSEC dataset.

### ISSUE THREAD

**Issue by UtharaKeerthan** [neuromorphs/tonic#150]
Hi, 
Thanks a lot for adding the DSEC dataset. I would like to download a specific sequence from the DSEC dataset, say interlaken_00_c. May I know the syntax for it ? 
Using, 
**import tonic
dataset = tonic.datasets.DSEC(save_to='./data', recording='zurich_city_04_b')**
doesnt work.

**Comment by biphasic** [comment]
Hey,
I added your desired functionality in https://github.com/neuromorphs/tonic/commit/b9da8932643c7ec29f2d4e54927600a5feeeb892. Just pull the latest tonic release 1.0.2 and you should be able to run your lines above. Also check documentation here: https://tonic.readthedocs.io/en/latest/reference/datasets.html#dsec

**Comment by UtharaKeerthan** [comment]
Thanks a lot.

**Comment by biphasic** [comment]
let me know if you experience issues with it!
