### ISSUE TITLE
Denoising on the DSEC dataset fails

### ISSUE THREAD

**Issue by UtharaKeerthan** [neuromorphs/tonic#153]
Hi,
I downloaded the zurich_city_04_b dataset and I extracted the events_left from the dataset.
When I denoise this events, I get the following error, 
File "~\lib\site-packages\tonic\functional\denoise.py", line 19, in denoise_numpy
 **assert "x" and "y" and "t" in events.dtype.names
TypeError: argument of type 'NoneType' is not iterable**

I checked the events.dtype.names, its None rather than the list of channels (x,y,t). 
![image](https://user-images.githubusercontent.com/49371846/140064801-98ddf6b7-a76d-472b-90a9-1717006e67d8.png)

Please provide your feedback

**Comment by biphasic** [comment]
hello, this should be fixed now. Could you try again please?

**Comment by UtharaKeerthan** [comment]
Hi, Thanks for the update. It works now. But When I print the sensor size from the dataset I get (346, 260, 2). But the event frames in the DSEC dataset have the resolution of 640x480, Am I missing something here ?
