### ISSUE TITLE
Sensor resolution mismatch in the DSEC dataset.

### ISSUE THREAD

**Issue by UtharaKeerthan** [neuromorphs/tonic#157]
Hi, 
I'm using the DSEC dataset. 
I get the following error when I try to get the frames from the DSEC events. 
![image](https://user-images.githubusercontent.com/49371846/140752238-8db0c31c-2fd3-42f8-8dc7-8dde632a36b7.png)

When I print the sensor size from the dataset,  I get (346, 260, 2).
![image](https://user-images.githubusercontent.com/49371846/140752853-9dc6dab1-424b-4377-a92d-e6dd47c8e7e0.png)

But the event camera in the DSEC dataset have the resolution of 640x480.
![image](https://user-images.githubusercontent.com/49371846/140753165-1ce3827a-0b01-4982-ae61-166ce97bb9fa.png)

Is this the reason for the error above or am I missing something else ?

**Comment by biphasic** [comment]
@UtharaKeerthan you are right, this sensor size is incorrect. I fixed it in https://github.com/neuromorphs/tonic/commit/0146c900e587852e03b916255a170624fb51bf42

thanks a lot for reporting this stuff, I initially verified that the downloads work fine but didn't pick up the things you found. When working with long recordings such as this one, you might want to slice it into smaller chunks. I put up some tutorials on that, maybe you're interested: https://tonic.readthedocs.io/en/latest/tutorials/slicing.html

**Comment by UtharaKeerthan** [comment]
Thanks for the fix. Also thanks for the tutorial on slicing. Made the job easier for me. :)

**Comment by biphasic** [comment]
actually for your case the tutorial on large datasets might actually be more relevant: https://tonic.readthedocs.io/en/latest/tutorials/large_datasets.html which also includes slicing

**Comment by UtharaKeerthan** [comment]
Thanks
