### ISSUE TITLE
Error in slicing the DSEC dataset.

### ISSUE THREAD

**Issue by UtharaKeerthan** [neuromorphs/tonic#158]
Hi, 
I'm using the DSEC dataset. I wanted to slice only a smaller part of the dataset. But I get the following error, when I do it,
![image](https://user-images.githubusercontent.com/49371846/143021888-596fbba8-8aac-4c33-985a-37d439a1ad22.png).

The following is the cod snippet that I'm using. 

```
dataset = tonic.datasets.DSEC(save_to='./in/data', recording='zurich_city_04_b')
sensor_size = tonic.datasets.DSEC.sensor_size
print('Slicing events...')
slicing_time_window = 25000
slicer = SliceByTime(time_window=slicing_time_window)
sliced_dataset = SlicedDataset(dataset, slicer=slicer, metadata_path='./metadata/DSEC')
```

It would be a great help, if you can provide  a sample code for slicing with the DSEC dataset.

**Comment by biphasic** [comment]
Hey, thanks for flagging this. I will look into this

**Comment by UtharaKeerthan** [comment]
Sure, thanks a lot. Also the DSEC dataset provides a time offset with each dataset. That has to be added with the timestamps of the individual events. This is done for efficient memory management. Right now the tonic dataset downloader does not get the t_offset values from the dataset. 

Would be better if that is also extracted from the data. Thanks in advance.

**Comment by biphasic** [comment]
Hey,
datasets in tonic always return a tuple of (data, targets). The way you try to do the slicing only works if data contains events only. In the case of DSEC, data contains nested tuples of multiple things, see [here](https://tonic.readthedocs.io/en/latest/reference/datasets.html#dsec). In your stacktrace, the slicer tries to access data["t"], thinking that data is an array of events, but then data is actually a tuple. You will therefore have to write a wrapper function that applies the slicer to the events of your choice. There is a tutorial that deals with this here: https://tonic.readthedocs.io/en/latest/tutorials/large_datasets.html

**Comment by UtharaKeerthan** [comment]
Hi, Thanks a lot for the response. I will write a custom wrapper for the DSEC dataset.

**Comment by biphasic** [comment]
and regarding the time offset, currently this offset is subtracted from all events. When you say that you want the offset extracted from the data, what do you mean by that?
