### ISSUE TITLE
Could not import Dataset package

### ISSUE THREAD

**Issue by UtharaKeerthan** [neuromorphs/tonic#159]
Hi, 
I'm trying to wrap my own recording of events and images.  When I use the import statements from the tutorial, 
```
import numpy as np
import h5py
from tonic.datasets import Dataset
```
I get an error that **Cannot find reference for Dataset**. Im using a pycharm virtual environment for this process and I installed tonic package successfully. I can import other packages like slicer and transforms. Am I missing something here ?

**Comment by biphasic** [comment]
Hey, I saw that this is not correct in the tutorial and I'll update it. It should be
```
from tonic import Dataset
```
and it's not strictly necessary to inherit from a Tonic Dataset class, just as long as you provide data in the right format. I will update the tutorial. Thanks for flagging this one!

**Comment by biphasic** [comment]
now executing notebook to make sure all the code in the docs works f7fe6fe63d69f330ff246b41fefc2a0166e31dce
