### ISSUE TITLE
Modifying transforms after applying them the first time not working

### ISSUE THREAD

**Issue by jeshraghian** [neuromorphs/tonic#160]
Hey Gregor + Tonic team,

When I try to modify the transforms a second time (after the first time I apply them), it seems the DataLoader objects don't want to be updated. I ran into this issue while trying to run some randomized parameter sweeps, and wanted to test the effect of `n_time_bins`. 

E.g.,:

```
n_time_bins = 25

frame_transform = transforms.Compose([transforms.ToFrame(sensor_size=sensor_size,
                                      n_time_bins=n_time_bins)])
transform = tonic.transforms.Compose([torch.from_numpy])
                                    
trainset = tonic.datasets.NMNIST(save_to='./data', transform=frame_transform, train=True)
cached_trainset = CachedDataset(trainset, transform=transform, cache_path='./cache/nmnist/train')
trainloader = DataLoader(cached_trainset, batch_size=batch_size, collate_fn=tonic.collation.PadTensors())

```

E.g., the following snippet:
`print(trainloader.dataset[0][0].size())` returns a tensor with 25 time steps.

But if I rerun the above, and change `n_time_bins` to any other value, `trainloader` is still stuck with 25 time steps. 

I've tried assigning the dataset, transforms, dataloaders etc. new names, though no luck there either. Let me know if there's a straightforward workaround for this! Love your work.

**Comment by sheiksadique** [comment]
Hi Json,
This is happening because of the use of CachedDataset in your data
pipeline.

Cached dataset loads data from the specified cache and only generates new
data if it is not found.

So if you change your transforms before caching, you will either have to
discard it or specify a new name for the cache folder.

Hope that makes sense.

**Comment by jeshraghian** [comment]
Hi @sheiksadique, that makes perfect sense. Thanks a lot for the quick reply.

**Comment by biphasic** [comment]
thanks for the question Jason, I will make it clearer in the [documentation](https://tonic.readthedocs.io/en/latest/reference/data_classes.html#cacheddataset) as this is something that other people ran into as well.
