### ISSUE TITLE
Add: ToSparseTensor transform function

### ISSUE THREAD

**Issue by MoShrank** [neuromorphs/tonic#161]
Hey!
It doesn't make sense to that you remove a function that is actually quite useful especially when it comes to working with spike train data. I suggest to add it again because: a) its helpful when data in dense format is larger than available memory, b) some operations supported by smaller libraries still work on sparse tensors.
Thanks!

**Comment by biphasic** [comment]
Hey,
so normally if you're training on larger dense tensors than are suitable for GPU memory, I would recommend slicing the recording into smaller chunks. Out of interest, what smaller libraries are you using in combination with sparse tensors?

**Comment by biphasic** [comment]
let me know of your use case and I'll consider bringing sparse tensors back. Closing this for now
