### ISSUE TITLE
Issue on page /reference/transformations.html

### ISSUE THREAD

**Issue by UtharaKeerthan** [neuromorphs/tonic#162]
Question on Transformation of events to Frames:

Hi, As per the documentation, the transformation of events to frames is an accumulation of events.
And we get two frames as the output, 1 for the positive events and one for negative events.

What exactly is the accumulation here ? if a positive event occurs at a particular pixel point twice within the window(time or number of events), will the accumulated value of the positive frame at that pixel point be 2 or 1?

**Comment by biphasic** [comment]
it will be the total number of pixels that occured within that time frame, so 2

**Comment by biphasic** [comment]
added a clarification in f7fe6fe63d69f330ff246b41fefc2a0166e31dce
