### ISSUE TITLE
The time_steps equals 0 after slicing and to_frame

### ISSUE THREAD

**Issue by wangkgege** [neuromorphs/tonic#181]
I transformed  ibm gesture events to frame (frame shape: time_steps * 2 * 128 * 128) using SliceByEventCount and ToFrame.
But time_steps equals to 0 in some frames. 

I transformed events data using following codes:
slicer = SliceByEventCount(event_count=3000, overlap=0, include_incomplete=False)
to_frame_transform = transforms.ToFrame(sensor_size=(128,128,2), time_window=10000)
dataset = SlicedDataset(test_datasets, slicer, transform=to_frame)

And I found that if the time difference of one sliced events is lower than time_window passed to class ToFrame, then got time_steps equals to 0. It would be great to give user a warning or error when he run into the situation.

You can reproduce the problem using following codes.

from tonic import SlicedDataset
from tonic.datasets import DVSGesture
from tonic.slicers import SliceByEventCount

test_datasets = DVSGesture(save_to='/workspace/Data', train=False, transform=None, target_transform=None)
slicer = SliceByEventCount(event_count=3000, include_incomplete=False)
to_frame = None
dataset = SlicedDataset(test_datasets, slicer, transform=to_frame)
time_window = 10000
for inx, (events, _) in enumerate(dataset):
    times = events['t']
    if (times[-1] - times[0]) < time_window:
        print(f'inx: {inx}')
        break

**Comment by biphasic** [comment]
Hey @wangkgege sorry for the late response. This behaviour is intended and in fact there is no guarantee that you will receive any amount of time steps when you slice by event count. 
If you want to have a specific amount of time steps in each slice, you should SliceByTime.

**Comment by biphasic** [comment]
closing this for now
