### ISSUE TITLE
For CIFAR10DVS, Tonic keeps unzipping the dataset even if it is already decompressed.

### ISSUE THREAD

**Issue by fabhertz95** [neuromorphs/tonic#185]
Hi everyone. I am experiencing an issue with the CIFAR10DVS. In particular, when I run the first time my script, the dataset is downloaded and unzipped. In the following runs, Tonic checks that the dataset has been downloaded and, then, it unzippes the dataset again. Deleting the `.zip` file leads to Tonic downloading again the dataset. 

The code is the following:
```
import tonic
ds = tonic.datasets.CIFAR10DVS(save_to="./data")
```
I am using Tonic version `1.0.16` from `conda-forge`, with Python version 3.9 on Linux.

**Comment by biphasic** [comment]
thank you for fixing it in #186
