### ISSUE TITLE
ASLDVS file_md5 seems broken

### ISSUE THREAD

**Issue by jrfinkbeiner** [neuromorphs/tonic#197]
Hi,

I just tried to download the ASL-DVS via `tonic.datasets.ASLDVS`.
However, the download fails as it complains about a wrong md5 signature. It expects `"20f1dbf961f9a45179f6e489e93c8f2c"` which is hardcoded into the class, but on two different systems I get `"33f8b87bf45edc0bfed0de41822279b9"` using `tonic.download_utils.calculate_md5`.

In both cases I am using a freshly installed tonic version via `pip install tonic`, tonic version '1.0.20'. 

Running something this should give the result:

```python
import tonic
try:
    tonic.datasets.ASLDVS(save_to="./")
except Exception as e:
    print(e)
actual_md = tonic.download_utils.calculate_md5("./ASLDVS/ASLDVS.zip")
print(actual_md)
```

It would be nice if somebody could check whether I am wrong, or whether the attribute `file_md5` in the class `tonic.datasets.ASLDVS` is actually wrong.

Thanks,
Jan

**Comment by fabhertz95** [comment]
Hi @jrfinkbeiner. I receive the same error when using Tonic to download it. 
As you said, probably the MD5 signature has changed (is it possible, though?) and needs to be updated in the source code of the dataset class. Are you able to manually download the dataset from the internet and calculate its MD5 signature? The link should be [this one](https://www.dropbox.com/sh/ibq0jsicatn7l6r/AACNrNELV56rs1YInMWUs9CAa?dl=0).

**Comment by jrfinkbeiner** [comment]
@fabhertz95 I did that, the manual download (via the link provided in the dataset class), and I get the same signature as mentioned above "33f8b87bf45edc0bfed0de41822279b9", which is different from the one in the class.

**Comment by fabhertz95** [comment]
Nice! Well, you can open a PR that corrects the MD5 signature and passes all the tests, if you want. I would wait for @biphasic opinion but I think this is the best option.

**Comment by biphasic** [comment]
thank you @jrfinkbeiner @fabhertz95. The hash is hardcoded to guard against corrupted files in any way, see https://github.com/pytorch/vision/blob/main/torchvision/datasets/mnist.py#L41 for an example in torchvision. The original data didn't change from what it looks like (although we wouldn't know if a file was deleted for example). Could be that the way Dropbox is zipping the folders changed slightly. In any case thanks for reporting it and please open a PR with the new hash. Thank you!

**Comment by jrfinkbeiner** [comment]
Sounds good, will do.

**Comment by biphasic** [comment]
mentioning issue https://github.com/neuromorphs/tonic/issues/146 too
