### ISSUE TITLE
Support for LightningDataModule

### ISSUE THREAD

**Issue by sheiksadique** [neuromorphs/tonic#209]
It would be very convenient and also promote PyTorch users to maintain good programming practices by adding a submodule/wrapper for the default Tonic datasets.

Something like `tonic.datasets.pl....`

**Comment by biphasic** [comment]
Unfortunately such a lightning module would be quite different for every dataset supported in Tonic. Things like slicing and caching are very much setup-dependent and it's hard to find a setup that works for everyone. If I expose all of the options in the constructor, then the advantage of a Lightning dataset is lost. Nevertheless I do think that it'd be a good idea to provide some standardized way of a dataset, which will then be the 'tonic benchmark' version. I'll close this for now
