### ISSUE TITLE
Spiking Tactile MNIST dataset

### ISSUE THREAD

**Issue by biphasic** [neuromorphs/tonic#210]
https://arxiv.org/abs/2005.04319

**Comment by fabhertz95** [comment]
@biphasic do you think we can try to use data pipes (#201) for this dataset?

**Comment by biphasic** [comment]
That's a great idea :) Do you maybe want to look into this together during a hack session? We could check out how PyTorch data works

**Comment by fabhertz95** [comment]
Definitely!

**Comment by fabhertz95** [comment]
@biphasic did you take a look at the paper? I am looking at the dataset and I have found a strange timestamp expressed in seconds:
![image](https://user-images.githubusercontent.com/45739782/185670675-33588d11-421c-4fd1-a695-491e141ea0e6.png)
That's some CERN-like time resolution right there :) I was thinking about using microseconds timestamps (i.e. multiplying that value by `1e6`), but what to do with those additional digits? I would simply discard them.

**Comment by biphasic** [comment]
thanks for looking into this. Yes this looks like second resolution, please go ahead as you suggested! It's clearer for users if all timestamps in tonic are microseconds.

**Comment by fabhertz95** [comment]
Moreover, some samples have multiple events (at most 2) associated to the same timestamp. How is it better to handle this? Should I decouple the event in multiple events with the same time stamp?

**Comment by fabhertz95** [comment]
Should we put STMNIST in the documentation as experimental?

**Comment by biphasic** [comment]
Yes a good idea! We just need to find a way to document how to use it. Maybe a readme.md in the tonic.prototype folder? The current datasets.rst in the docs folder only includes classes that are part of the package, but the prototypes folder is not part of the package. I would say either the readme and then people have to check it on GitHub or we include the prototypes in the package and then we might get to render docstrings in the documentation on readthedocs.
I say it's your call :)


Le 26 août 2022 17:20:58 GMT+01:00, Fabrizio Ottati ***@***.***> a écrit :
>Should we put STMNIST in the documentation as experimental?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/neuromorphs/tonic/issues/210#issuecomment-1228690284
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fabhertz95** [comment]
Well, I would say that a README for now is enough :) When torchdata will be stable, we will think about including it in the package official documentation.

**Comment by biphasic** [comment]
I would say this works now, doesn't it?

**Comment by fabhertz95** [comment]
I would say so!
