### ISSUE TITLE
The sensor_size of some datasets is none

### ISSUE THREAD

**Issue by ZHOUPHui** [neuromorphs/tonic#221]
I want to use NCAR in HATS, but I don’t know how to get the sensor_size of NCAR, because the size of every sample is different.

**Comment by fabhertz95** [comment]
Hi! If you go on Prophesee website, you'll see that they used [this sensor](https://ieeexplore.ieee.org/document/5648367), which is a 304x240 one. Hence, you can use that as sensor size for the NCARS dataset. If you use this size with HATS, you will get a very large file in th end. You can reduce by going through the dataset one time to estimate maximum and mimum width/height of the samples and, then, use those as sensor size for the HATS algorithm.

**Comment by biphasic** [comment]
they took the unfortunate decision to use crops of different sizes...
