### ISSUE TITLE
Some questions about CIFAR10DVS

### ISSUE THREAD

**Issue by ZHOUPHui** [neuromorphs/tonic#224]
I download cifar10dvs from other web， but I found that the format of the file is aedat，not aedat4. The code of tonic maybe use to deal with aedat4 and when I use decoder to read aedat files，something is wrong.I wonder if they are different and if the origin format of this database is aedat4.

**Comment by biphasic** [comment]
Hello @ZHOUPHui ,
the file format is always `filename.aedat`. The AEDAT version is specified in the header of the file, see here: https://gitlab.com/inivation/inivation-docs/blob/master/Software%20user%20guides/AEDAT_file_formats.md#aedat-40

Under the hood Tonic uses this library to read AEDAT v4 files: https://github.com/neuromorphicsystems/aedat
