### ISSUE TITLE
Porting datasets to new TorchData API

### ISSUE THREAD

**Issue by fabrizio-ottati** [neuromorphs/tonic#229]
See #201.

List of datasets to be ported:
- [x] NMNIST. 
- [x] STMNIST. 
- [x] NCARS.
- [ ] ASLDVS.
- [ ] CIFAR10-DVS.
- [ ] DVGGesture.
- [ ] NCALTECH101.
- [ ] POKERDVS.
- [ ] SMNIST.
- [ ] DVSLip.
- [ ] SHD.
- [ ] SSC.
- [ ] DAVISDATA.
- [ ] DSEC.
- [ ] MVSEC.
- [ ]  TUMVIE.
- [ ] VPR.

**Comment by biphasic** [comment]
In the end I think we don't need to convert most of the datasets. For most classification datasets, one can just use an IterableWrapper like so
```
import tonic
from torchdata.datapipes.iter import IterableWrapper

dp = IterableWrapper(tonic.datasets.NMNIST('data'))
dp = dp.filter(lambda data: data[1]==0) # only get samples with label 0
``` 
I think where the new API might make the most sense is for DSEC and TUMVIE, but even for those, DataLoader2 is not super mature yet to justify a migration and if the new API is much more suitable for those, also IterableWrappers can be used.

**Comment by biphasic** [comment]
closing this for now because torchdata development is on hold https://github.com/pytorch/data/issues/1196
