### ISSUE TITLE
Add Gen1 automotive dataset from Prophesee

### ISSUE THREAD

**Issue by fabrizio-ottati** [neuromorphs/tonic#230]
The dataset is available [here](https://www.prophesee.ai/2020/01/24/prophesee-gen1-automotive-detection-dataset/). [expelliarmus](https://github.com/open-neuromorphic/expelliarmus) has to be used to read the binary data and the TorchData API (see #201) to create the dataset class.

**Comment by biphasic** [comment]
added in 2a3afa83b8cfaf7f2dd9399ea269af764cbbf938
