### ISSUE TITLE
ToFrame silently merges polarities when sensor_size indicates single polarity (e.g. [128,128,1])

### ISSUE THREAD

**Issue by biphasic** [neuromorphs/tonic#244]
this line is the culprit
https://github.com/neuromorphs/tonic/blob/develop/tonic/functional/to_frame.py#L61

This was introduced to make sure that in the case of audio samples all polarities have values 0 instead of 1. We need to introduce a check that raises a warning if there are more than 1 polarities present in the data

**Comment by fabrizio-ottati** [comment]
BTW the guys in the lab told me that we should make explicit that the ToFrame tensors are not binary but they accumulate the spikes to compress them in time windows

**Comment by biphasic** [comment]
I updated the ToFrame docstring to include a statement about binary frames 03d794182ac22e6ce09f8e724632571fc659359c

**Comment by biphasic** [comment]
fixed in 26ac71f695a1c8e31ee4175aaeea95b9bda7fa1e
