### ISSUE TITLE
How to convert dataset to numpy

### ISSUE THREAD

**Issue by mosfe** [neuromorphs/tonic#251]
Hello, the tonic and rockpool are useful tools to process spiking data.
However, what should I do if I want to convert the dataset to numpy and save as the npy file?
for example,
train_data = datasets.SHD(download_dir, train=True, transform=transform)
I can get the SHD dataset using the codes above, and train the network by iteration. I can also see the data through train_data[0][0] or train_data[0][1].
But how can I get all labels of the dataset? I can get one of it through index by train_data[0][1]. The spikes also has this problem.
If you can tell me how to convert the train_data to npy file, I would be very thanks.
Hope for your reply.

**Comment by biphasic** [comment]
Hey @mosfe , simply use a list comprehension to get all the labels/events

```
train_events = [sample[0] for sample in train_data]
train_labels = [sample[1] for sample in train_data]
```
