### ISSUE TITLE
Failed to download pokerDVS

### ISSUE THREAD

**Issue by CheungBH** [neuromorphs/tonic#253]
Thanks for your great work.  
I am trying to download pokerDVS but it fails:
**urllib.error.HTTPError: HTTP Error 504: Gateway Time-out**
Could you help check for it? Thank you

**Comment by CheungBH** [comment]
> Hey @CheungBH , I'm glad you're finding it useful! That dataset used to be hosted on https://www.neuromorphic-vision.com/public/ but given that that lab ceased to exist, it's likely that it has something to do with the zip file becoming unavailable. It'll need uploading elsewhere

@biphasic Thank you for your reply. Would you please tell me once the dataset is available?
Thank you

**Comment by tobidelbruck** [comment]
Hi All, Bernabe just wrote me to tell me that poker-dvs is available

Hi Tobi,

Our Poker-DVS is here: 
http://www2.imse-cnm.csic.es/neuromorphs/index.php/POKER-DVS-Database

and we have other database here: 
http://www2.imse-cnm.csic.es/neuromorphs/index.php/Event-Based-Vision-Databases

What exactly should we fix?

cheers,

Bernabe


-- 
Prof. Tobi Delbruck, Co-Director, Sensors Group: http://sensors.ini.uzh.ch, YouTube: https://www.youtube.com/channel/UC70-pVoJ4pwIAxqpgcR7oxg
Inst. for Neuroinformatics, UZH-ETH Zurich: http://www.ini.uzh.ch
Building 55, Room G84, Winterthurerstr. 190, CH-8057 Zurich, Switzerland
Tel lab +41 44 635 3038, Swiss cell +41 76 629 1500 (whatsapp), USA cell +1 626 510 2646, skype tobidelbruck

**Comment by CheungBH** [comment]
> Hi All, Bernabe just wrote me to tell me that poker-dvs is available Hi Tobi, Our Poker-DVS is here: http://www2.imse-cnm.csic.es/neuromorphs/index.php/POKER-DVS-Database and we have other database here: http://www2.imse-cnm.csic.es/neuromorphs/index.php/Event-Based-Vision-Databases What exactly should we fix? cheers, Bernabe
> […](#)
> -- Prof. Tobi Delbruck, Co-Director, Sensors Group: http://sensors.ini.uzh.ch, YouTube: https://www.youtube.com/channel/UC70-pVoJ4pwIAxqpgcR7oxg Inst. for Neuroinformatics, UZH-ETH Zurich: http://www.ini.uzh.ch Building 55, Room G84, Winterthurerstr. 190, CH-8057 Zurich, Switzerland Tel lab +41 44 635 3038, Swiss cell +41 76 629 1500 (whatsapp), USA cell +1 626 510 2646, skype tobidelbruck

@tobidelbruck Thanks for your reply.
Actually, I failed to download the dataset automatically when initializing the dataset. I noticed here
**https://github.com/neuromorphs/tonic/blob/9fbcaa776c457af5ef378b82faa2619c3f5c90f3/tonic/datasets/pokerdvs.py#L34**
that the URL for dataset downloading is 
"https://www.neuromorphic-vision.com/public/downloads/pips_train.tar.gz" and "https://www.neuromorphic-vision.com/public/downloads/pips_test.tar.gz".
However, a 504 Gateway Time-out occurs while accessing this site.

<img width="843" alt="Screenshot 2023-05-30 at 11 50 41 PM" src="https://github.com/neuromorphs/tonic/assets/39186017/94643da7-33a8-480f-8687-7801702dfe49">

**Comment by tobidelbruck** [comment]
The direct link to the files is 
http://www2.imse-cnm.csic.es/caviar/POKER_DVS/

The webpage is 
http://www2.imse-cnm.csic.es/neuromorphs/index.php/POKER-DVS-Database

I don't know about code that might hardcode the location.

I asked Bernabe to comment directly.

**Comment by biphasic** [comment]
Hey all, the link in the Tonic dataset points to a pre-processed version of the dataset because if I remember correctly the original recordings contained multiple card flips in one file. If we use the original download link then we'll have to introduce some preprocessing code. Alternatively upload the pre-processed zip somewhere else.

**Comment by tobidelbruck** [comment]
Thanks to Bernabe and Sio! Sio says:

> Hi Tobi,
>
> How are doing? The link in the github code from Gregor points to a 
> server of ours. unfortunately, it was been shutdown.
> The best is to use directly the data from Bernabé’s.
>
> Bests,
> Sio
>
