### ISSUE TITLE
DVSGesture download url not working

### ISSUE THREAD

**Issue by minghui-liu** [neuromorphs/tonic#255]
Cannot download DVSGesture dataset using

```
train_ds = spikedata.DVSGesture("dataset/dvs_gesture_train", train=True)
test_ds = spikedata.DVSGesture("dataset/dvs_gesture_test", train=False)
```

The download url [https://www.neuromorphic-vision.com/public/downloads/ibmGestureTrain.tar.gz](https://www.neuromorphic-vision.com/public/downloads/ibmGestureTrain.tar.gz) seems to be down.

**Comment by biphasic** [comment]
thank you for reporting it! I will change the host link

**Comment by biphasic** [comment]
Hey, I just saw that the DVSGesture dataset is hosted at figshare and perfectly available. https://figshare.com/ndownloader/files/38020584
Are you using a recent version of Tonic?
