### ISSUE TITLE
Some transforms won't work with SHD (and possibly other audio datasets)

### ISSUE THREAD

**Issue by JannKrausse** [neuromorphs/tonic#293]
Hi *,

I am currently implementing data augmentation for by neuromorphic datasets using the tonic transforms. However, I found that the UniformNoise and SpatialJitter transforms produce errors when applying them to the SHD dataset (they can be easily reproduced by changing the dataset name to SHD in the examples given on the tonic website).

For completeness:

- trying to apply UniformNoise to SHD throws a ValueError: "Single polarity sensor, but events contain both polarities."
- trying to apply SpatialJitter to SHD throws an AssertionError: "assert "x" and "y" in events.dtype.names."

I understand that I am trying to apply transforms that might be meant for visual event streams to audio data, but to me it makes sense applying them to SHD or SSC also, when assuming that the frequency channels represent the spatial dimension.

Please help 😅

**Comment by JannKrausse** [comment]
I think I found the reason for my problem. The representation of the events is actually different for vision and audio tasks. Assuming that the above transforms were written to alter events of vision tasks, it is no wonder that this will not work for audio tasks.
The easiest solution to that - and what I've done now - is to write custom transforms.

Best, Jann 😊
PS: Leaving this open to be confirmed by a developer

**Comment by biphasic** [comment]
Hey Jann,
Regarding the errors you're listing:

> trying to apply UniformNoise to SHD throws a ValueError: "Single polarity sensor, but events contain both polarities."

My guess is that you set the sensor_size to something like (x, y, 1) but the polarity channels contains both zeros and ones, hence the message.

> trying to apply SpatialJitter to SHD throws an AssertionError: "assert "x" and "y" in events.dtype.names."

This is indeed meant for events with x and y channel for the moment, but happy to look at a PR that generalises it to just x as well.
